name: Release airflow configs
on:
  push:
    branches:
      - CBILL-5758
jobs:
  release-airflow-configs:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Check Out
        uses: actions/checkout@v1
      - name: List Files after check out
        run: |
          pwd
          ls -a
          cd airflow/dags/internal/ && tar zcvf ../../../airflowcfg.tgz *
          ls -a
          echo "go to the the root directory"
          cd ../../..
          ls -a