name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: nginx:1.20.2-alpine
    steps:
      - name: Simple commands
        run: |
          pwd
          ls -la


