name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: nginx:1.20.2-alpine
    steps:
      - name: Simple commands
        run: |
          pwd
          ls -la

      # Get files from the ripository like "script.sh"
      - uses: actions/checkout@v1

      - name: Run a separate script.sh
        uses: nginx:1.20.2-alpine
        run: ls -la
        with:
          entrypoint: ./script.sh
          args: "Another test string"


