name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: hello-world
    steps:
      - name: Simple commands
        run: |
          pwd
          ls -a
          lsb_release -a


