
name: "File change monitor"
on:
  push:
    paths:
      - 'action-change.json'


jobs:
  File-change-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
        
      - name: List Files
        run: |
          pwd
          ls
          
      - name: Read VARS
        run: |
          # Read approved image versions
          IMAGE_VER_FILE="action-change.json"

          echo IMAGE_PROD_VERSION=`jq '.prod' $IMAGE_VER_FILE`
          echo IMAGE_RELEASE_VERSION=`jq '.release' $IMAGE_VER_FILE`
          echo IMAGE_DEV_VERSION=`jq '.dev' $IMAGE_VER_FILE`
          
          echo IMAGE_PROD_VERSION = $IMAGE_PROD_VERSION
          echo IMAGE_RELEASE_VERSION = $IMAGE_PROD_VERSION
          echo IMAGE_DEV_VERSION = $IMAGE_DEV_VERSION
