name: "Access GITHUB_OUTPUT values"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Env files usage.
        type: choice
        required: true
        options: [ Press run to start ]
        default: 'Press run to start'
        
jobs:
    job1:
      name: action configuration
      runs-on: [ubuntu-latest]
      
      # Use outputs to access from the job2
      outputs:
        action: ${{ steps.req.outputs.action }}
        version: ${{ steps.req.outputs.version }}
        deployed: ${{ steps.req.outputs.deployed }}

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Set vars
          id: req
          run: | 
          
              # SET VARS:
              deployed=true
              action=upgrade
              version=1.133.331.31
              CURRENT_DATE=`date +"%Y%m%d%H%M"`
              VTAG="${CURRENT_DATE}"
              
              # Save in GITHUB_OUTPUT https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
              
              echo "version=${version}"  >> "$GITHUB_OUTPUT"             
              echo "deployed=${deployed}" >> "$GITHUB_OUTPUT"
              echo "action=${action}" >> $GITHUB_OUTPUT
              
              echo "#Creating image <${CURRENT_DATE}> # :rocket:" >> $GITHUB_STEP_SUMMARY
                  
        - name: Print environment
          run: |
            echo 'Access VARS in the same job'
            
            echo "deployed = ${{ steps.req.outputs.deployed }}"
            echo "version = ${{ steps.req.outputs.version }}"
            echo "action = ${{ steps.req.outputs.action }}"
            echo "##Work in progress" >> $GITHUB_STEP_SUMMARY
            echo "1st - DONE :ok:" >> $GITHUB_STEP_SUMMARY 
            echo "2st - DONE :ok:" >> $GITHUB_STEP_SUMMARY 
            
            
        - name: Set color
          id: random-color-generator        
          run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
         
        - name: Get color
          run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
    job2:
        name: pre action validation
        needs: job1
        runs-on: [ubuntu-latest]
        
        steps:
          
        - name: Print environment job2
          run: |
            echo 'Access VARS from different job'
            
            echo "deployed = ${{ needs.job1.outputs.deployed }}"
            echo "version = ${{ needs.job1.outputs.version }}"
            echo "action = ${{ needs.job1.outputs.action }}"
            echo "Print environment job2 vars done! :rocket:" >> $GITHUB_STEP_SUMMARY
            
        
    
      
    
