name: "Schedule Test v2"
on:
  schedule:
    - cron: '0 2 * * *' # At 02:00 every night
#    - cron: '0 2 * * 7' # At 02:00 on Sunday
#  push:
##    tags:
##      - "[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+-test-dockerbuild"
##      - "[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+-dockerbuild"
#    branches:
#      - CBILL-5989


jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Check Out
        uses: actions/checkout@v1
      - name: List Files after check out
        run: |
          pwd
          ls -a
          # To get commit ID
          echo $GITHUB_SHA

          echo "GITHUB_REPOSITORY = " $GITHUB_REPOSITORY
          echo "GITHUB_WORKSPACE = " $GITHUB_WORKSPACE
          echo "github.token = ${{ github.token }}"
