name: Schedule Test v2

on:
  schedule:
  - cron: '*/10 * * * *'


jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Check Out
        uses: actions/checkout@v1
      - name: List Files after check out
        run: |
          pwd
          ls -a
          # To get commit ID
          echo $GITHUB_SHA

          echo "GITHUB_REPOSITORY = " $GITHUB_REPOSITORY
          echo "GITHUB_WORKSPACE = " $GITHUB_WORKSPACE
          echo "github.token = ${{ github.token }}"
