name: Shell Commands

#on: [push]

on:
  push:
    branches:
      - master
      - develop
#    taq:
#      - v1.*

#    path:
#      - '**.js'

jobs:
  run-windows-commands:
    runs-on: windows-latest
    # windows command will be run only after 'run-shell-command is completed
    needs: ['run-shell-command']
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash